<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="245" started-at="2019-07-01T11:12:23Z" finished-at="2019-07-01T11:12:23Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="245" started-at="2019-07-01T11:12:23Z" finished-at="2019-07-01T11:12:23Z">
      <class name="SeleniumTestNG.ParameterbyDataProvider">
        <test-method status="FAIL" signature="HardAssert()[pri:0, instance:SeleniumTestNG.ParameterbyDataProvider@523884b2]" name="HardAssert" duration-ms="68" started-at="2019-07-01T11:12:23Z" finished-at="2019-07-01T11:12:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ these are not equal co they are diferent  expected [harshil] but found [shilpa ]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError:  these are not equal co they are diferent  expected [harshil] but found [shilpa ]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at SeleniumTestNG.ParameterbyDataProvider.HardAssert(ParameterbyDataProvider.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HardAssert -->
        <test-method status="PASS" signature="Softassert()[pri:0, instance:SeleniumTestNG.ParameterbyDataProvider@523884b2]" name="Softassert" duration-ms="41" started-at="2019-07-01T11:12:23Z" finished-at="2019-07-01T11:12:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Softassert -->
      </class> <!-- SeleniumTestNG.ParameterbyDataProvider -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
